schema_version = "1.0.0"
id = "LegendGenerator"
version = "2.0.0"
name = "Legend Generator"
author = "José Marín"
tagline = "Customizable Legends for Scientific Visualization in Blender"
description = """
v.2.0.0

"""
blender_version_min = "4.2.0"
license = ["free licensing"]
tags = ["Compositing", "Visualization"]
type = "add-on"
maintainer = "José Marín <marinfarinajose@gmail.com>"
